use std::time::SystemTime;

// Parameter struct to reduce function argument count
pub struct MetricFetchParams {
    pub metric_name: String,
    pub namespace: String,
    pub instance_id: String,
    pub unit: Option<String>,
}

// Helper structs to organize metric data
pub struct CoreMetrics {
    pub cpu_utilization: f64,
    pub cpu_history: Vec<f64>,
    pub timestamps: Vec<SystemTime>,
    pub database_connections: f64,
    pub connections_history: Vec<f64>,
    pub free_storage_space: f64,
    pub free_storage_space_history: Vec<f64>,
    pub read_iops: f64,
    pub read_iops_history: Vec<f64>,
    pub write_iops: f64,
    pub write_iops_history: Vec<f64>,
    pub read_latency: f64,
    pub read_latency_history: Vec<f64>,
    pub write_latency: f64,
    pub write_latency_history: Vec<f64>,
    pub read_throughput: f64,
    pub read_throughput_history: Vec<f64>,
    pub write_throughput: f64,
    pub write_throughput_history: Vec<f64>,
    pub network_receive_throughput: f64,
    pub network_receive_history: Vec<f64>,
    pub network_transmit_throughput: f64,
    pub network_transmit_history: Vec<f64>,
    pub swap_usage: f64,
    pub swap_usage_history: Vec<f64>,
    pub freeable_memory: f64,
    pub freeable_memory_history: Vec<f64>,
    pub queue_depth: f64,
    pub queue_depth_history: Vec<f64>,
}

pub struct AdvancedMetrics {
    pub burst_balance: f64,
    pub burst_balance_history: Vec<f64>,
    pub cpu_credit_usage: f64,
    pub cpu_credit_usage_history: Vec<f64>,
    pub cpu_credit_balance: f64,
    pub cpu_credit_balance_history: Vec<f64>,
    pub bin_log_disk_usage: f64,
    pub bin_log_disk_usage_history: Vec<f64>,
    pub replica_lag: f64,
    pub replica_lag_history: Vec<f64>,
    pub maximum_used_transaction_ids: f64,
    pub maximum_used_transaction_ids_history: Vec<f64>,
    pub oldest_replication_slot_lag: f64,
    pub oldest_replication_slot_lag_history: Vec<f64>,
    pub replication_slot_disk_usage: f64,
    pub replication_slot_disk_usage_history: Vec<f64>,
    pub transaction_logs_disk_usage: f64,
    pub transaction_logs_disk_usage_history: Vec<f64>,
    pub transaction_logs_generation: f64,
    pub transaction_logs_generation_history: Vec<f64>,
    pub failed_sql_server_agent_jobs_count: f64,
    pub failed_sql_server_agent_jobs_count_history: Vec<f64>,
    pub checkpoint_lag: f64,
    pub checkpoint_lag_history: Vec<f64>,
    pub connection_attempts: f64,
    pub connection_attempts_history: Vec<f64>,
}
