use super::metric_types::{AdvancedMetrics, CoreMetrics};
use crate::models::MetricData;

pub fn build_metric_data(core: CoreMetrics, advanced: AdvancedMetrics) -> MetricData {
    MetricData {
        timestamps: core.timestamps,
        cpu_utilization: core.cpu_utilization,
        cpu_history: core.cpu_history,
        database_connections: core.database_connections,
        connections_history: core.connections_history,
        free_storage_space: core.free_storage_space,
        free_storage_space_history: core.free_storage_space_history,
        read_iops: core.read_iops,
        read_iops_history: core.read_iops_history,
        write_iops: core.write_iops,
        write_iops_history: core.write_iops_history,
        read_latency: core.read_latency,
        read_latency_history: core.read_latency_history,
        write_latency: core.write_latency,
        write_latency_history: core.write_latency_history,
        read_throughput: core.read_throughput,
        read_throughput_history: core.read_throughput_history,
        write_throughput: core.write_throughput,
        write_throughput_history: core.write_throughput_history,
        network_receive_throughput: core.network_receive_throughput,
        network_receive_history: core.network_receive_history,
        network_transmit_throughput: core.network_transmit_throughput,
        network_transmit_history: core.network_transmit_history,
        swap_usage: core.swap_usage,
        swap_usage_history: core.swap_usage_history,
        freeable_memory: core.freeable_memory,
        freeable_memory_history: core.freeable_memory_history,
        queue_depth: core.queue_depth,
        queue_depth_history: core.queue_depth_history,

        // Advanced metrics
        burst_balance: advanced.burst_balance,
        burst_balance_history: advanced.burst_balance_history,
        cpu_credit_usage: advanced.cpu_credit_usage,
        cpu_credit_usage_history: advanced.cpu_credit_usage_history,
        cpu_credit_balance: advanced.cpu_credit_balance,
        cpu_credit_balance_history: advanced.cpu_credit_balance_history,
        bin_log_disk_usage: advanced.bin_log_disk_usage,
        bin_log_disk_usage_history: advanced.bin_log_disk_usage_history,
        replica_lag: advanced.replica_lag,
        replica_lag_history: advanced.replica_lag_history,
        maximum_used_transaction_ids: advanced.maximum_used_transaction_ids,
        maximum_used_transaction_ids_history: advanced.maximum_used_transaction_ids_history,
        oldest_replication_slot_lag: advanced.oldest_replication_slot_lag,
        oldest_replication_slot_lag_history: advanced.oldest_replication_slot_lag_history,
        replication_slot_disk_usage: advanced.replication_slot_disk_usage,
        replication_slot_disk_usage_history: advanced.replication_slot_disk_usage_history,
        transaction_logs_disk_usage: advanced.transaction_logs_disk_usage,
        transaction_logs_disk_usage_history: advanced.transaction_logs_disk_usage_history,
        transaction_logs_generation: advanced.transaction_logs_generation,
        transaction_logs_generation_history: advanced.transaction_logs_generation_history,
        failed_sql_server_agent_jobs_count: advanced.failed_sql_server_agent_jobs_count,
        failed_sql_server_agent_jobs_count_history: advanced
            .failed_sql_server_agent_jobs_count_history,
        checkpoint_lag: advanced.checkpoint_lag,
        checkpoint_lag_history: advanced.checkpoint_lag_history,
        connection_attempts: advanced.connection_attempts,
        connection_attempts_history: advanced.connection_attempts_history,
    }
}
